### ISSUE TITLE
Two checkboxes rendered

### ISSUE THREAD

**Issue by krisztian-fekete** [magento/magespecialist_ReCaptcha#48]
I've noticed that the `getIsInvisibleRecaptcha` returns `true` if the reCaptcha type in the configuration is *not* Invisible. Shouldn't this return true if it *is* invisible? This causes two checkboxes to be rendered on the Contact page, as the KnockoutJs template renders the second one if `getIsInvisibleRecaptcha` returns true.

### Preconditions
1. Magento 2.2.9
3. PHP 7.1
2. Msp_ReCaptcha 2.1.2

### Steps to reproduce
1. Enable ReCaptcha in Store > Configuration, Security
2. ReCaptcha type should be reCaptcha v2
3. Use in Contact should be Yes
4. Visit the contact page

### Expected result
1. A reCaptcha verification checkbox should be rendered

### Actual result
1. In addition to the reCaptcha verification box, an additional checkbox is rendered 

![alt text](https://i.ibb.co/vwFjpcV/recaptcha-checkboxes.png "checkbox")

**Comment by phoenix128** [comment]
Hello @krisztian-fekete ,
I checked you PR, but it is wrong and it breaks the ReCaptcha feature.
You are right there is a logical error in the definition of `getIsInvisibleRecaptcha`, but "luckily" we did a double mistake in inverting the logic in `reCaptcha.html` :) . Of course, I am going to fix it, but it is working.

Your issue is caused by a different problem: Seems the following CSS rules from `_module.less` are not applied or overridden in your theme:

```
.required-captcha.checkbox{
    position: absolute;
    display: block;
    visibility: visible;
    overflow: hidden;
    opacity: 0;
    width: 1px;
    height: 1px;
}
```

That checkbox is required for form validation, so it is correct to have it in "visible" ReCaptcha, but it should not be displayed.

**Comment by krisztian-fekete** [comment]
Hi @phoenix128 ,

You are correct, the theme is a child of the Sass implementation of Blank by snowdog, so the Less styling from `_module.less` was never applied, and that caused the issue (not the knockoutJs template). I added it to the custom theme as Sass and now the checkbox is hidden. Thanks :)

**Comment by phoenix128** [comment]
You are welcome ;)
